### ISSUE TITLE
[gromet] Improved representation of code comments in gromet metadata

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#239]
```[tasklist]
### Tasks
- [x] In coordination with @enoriega , decide on revised gromet structure for code comments as gromet JSON metadata
- [x] Release gromet_metadata_v0.1.7
  - [x] satisfied by <https://github.com/ml4ai/skema/issues/242>
```

**Comment by cl4yton** [comment]
This has been completed, by PR #243
