### ISSUE TITLE
[comment extraction] migrate to tree-sitter for comment extraction

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#266]
With our adoption of tree-sitter, we want to revisit how we approach comment extraction to easily scale extraction to new languages.  

Comments are captured in tree-sitter grammars and tree-sitter queries can be used to extract them (ex. `(comment)+`).

```[tasklist]
### Tasks
- [x] Replicate comment extraction functionality in Python using `tree-sitter`
- [x] Remove comment extraction service from skema-rs
- [x] Add REST endpoint to skema-py for comment extraction
- [ ] Update e2e.ipynb example to use skema-py endpoint for comment extraction
```

**Comment by adarshp** [comment]
@myedibleenso  - let's make a decision on this --- if we do go this route, then I'll close https://github.com/orgs/lum-ai/projects/6/views/1?pane=issue&itemId=31650999

**Comment by adarshp** [comment]
(since it would make sense for the comment extraction to be done as part of the PA pipeline which would already be using tree-sitter, instead of via the separate comment extraction service)

**Comment by vincentraymond-ua** [comment]
Personally, I would be in favor of handling comment extraction with tree-sitter. I briefly looked into this functionality when we started working with Fortran, and tree-sitter makes it pretty easy.

**Comment by myedibleenso** [comment]
My preference would be to handle this from tree-sitter as well moving forward.  Not only would that streamline gromet generation, it will make things easier to maintain as we grow to support additional frontends.

**Comment by adarshp** [comment]
Sounds good to me as well. I've closed https://github.com/orgs/lum-ai/projects/6/views/1?pane=issue&itemId=31650999.

**Comment by vincentraymond-ua** [comment]
@adarshp - Is there an example JSON schema for the output of the skema-rs comment extractor?

**Comment by myedibleenso** [comment]
@vincentraymond-ua , the REST API for `skema-rs` has an OpenAPI spec:

<img width="491" alt="image" src="https://github.com/ml4ai/skema/assets/1137472/c904933c-9b07-4b45-94c0-0a760f7c0fb3">

The **Comment extraction** section of https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/main/end-to-end-rest/notebooks/e2e.ipynb has some example response for a single file case.

**Comment by adarshp** [comment]
@myedibleenso  - there is OpenAPI documentation for the single-file extraction endpoint, but not for the zipfile extraction endpoint.

**Comment by myedibleenso** [comment]
## Update (7/25/2023)

- @vincentraymond-ua : migrating to a `tree-sitter`-based method for comment extraction will introduce an additional comment type (multi-line)
- still todo: verify `tree-sitter` output plays nicely with @titomeister 's unifier

**Comment by vincentraymond-ua** [comment]
Update (8/11/2023)

- Still working on finishing up comment extraction endpoints.
- Creating unit tests for comment extraction services and endpoints.

**Comment by vincentraymond-ua** [comment]
Update (8/15/2023)

Should have PR in by end of the week.

**Comment by vincentraymond-ua** [comment]
## Update (8/18/2023)
Submitted PR for this here: #398

This does not remove the existing Rust comment extractor, as it is still being used for comment unification in the code2fn rest endpoints. @titomeister and I should meet to discuss updating the comment unifier to support the new comment extraction format. Then we can submit a new PR to remove the Rust comment extractor.

**Comment by vincentraymond-ua** [comment]
## Update (8/25/2023) 

Remaining tasks resolved by #418. Working on creating a PR for updating e2e.ipynb.
