### ISSUE TITLE
[img2mml/rest] Load img2mml pytorch model once

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#280]
The REST API for eq2mml services relies on calls to [`get_mathml_from_bytes()`](https://github.com/ml4ai/skema/blob/9b7c26c165c149254901cf1feba089b54a0b458f/skema/img2mml/api.py#L9) when converting images of equations to pmml.  Internally, this function loads the necessary pytorch model for each call to the REST API.  To avoid this uncessary overhead and decrease latency, we should load the model once.  

## Proposal

- [ ] Define utility function to load model, set device, and load vocab  
- [ ] [Call utility function in `skema.img2mml.eq2mml`](https://github.com/ml4ai/skema/blob/9b7c26c165c149254901cf1feba089b54a0b458f/skema/img2mml/eq2mml.py#L57)
- [ ] Alter functions defined in `skema.img2mml.translate` and `skema.img2mml.api` as needed

### Details

Planned changes per file.

`skema/img2mml/utils.py`

```python
from skema.img2mml.translate import define_model
from logging import info
from dataclass import dataclass
from typing import List, Text

# Set logging level to INFO
logging.basicConfig(level=logging.INFO)

@dataclass
class Img2MMLModel:
  model: Image2MathML_Xfmer
  vocab: List[Text]

# FIXME: this default value for model_file is now out-of-date
def load_model(model_file: Text = "cnn_xfmer_OMML-90K_best_model_RPimage.pt", config_name: Text = "ourmml_xfmer_config.json") -> Img2MMLModel:
    # read config file
    cwd = Path(__file__).parents[0]
    config_path = cwd / "configs" / config_name
    with open(config_path, "r") as cfg:
        config = json.load(cfg)

    # read vocab.txt
    with open(cwd / "vocab.txt") as f:
        vocab = f.readlines()

    model_path = cwd / "trained_models" / model_file

    # set_random_seed
    set_random_seed(config["seed"])

    # select device
    device: Text = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    model: Image2MathML_Xfmer = define_model(
    config=config, vocab=vocab, device=device, model_type="xfmer").to(device)

    print("loading trained img2mml model...")

    if not torch.cuda.is_available():
        info("CUDA is not available; falling back to using the CPU.")
        model.load_state_dict(
            torch.load(model_path, map_location=torch.device("cpu"))
        )
    else:
        model.load_state_dict(torch.load(model_path))
```

`skema/img2mml/translate.py`
```python
from typing import Text
from skema.img2mml.utils import Img2MMLModel

def render_mml(img2mml_model: Img2MMLModel, imagetensor: torch.Tensor) -> Text:
  return evaluate(img2mml_model, imagetensor, device)

# TODO: change signatures for evaluate, etc to accept 
```

`skema/img2mml/eq2mml.py`
```python
from skema.img2mml.utils import Img2MMLModel, load_model

img2mml_model: Img2MMLModel = load_model(model_file="cnn_xfmer_OMML-90K_best_model_RPimage.pt", config_name="ourmml_xfmer_config.json")
```

`skema.img2mml.api.py`
```python
# change get_mathml_from_bytes(data: bytes) -> get_mathml_from_bytes(img2mml_model: Img2MMLModel, data: bytes)
```
