### ISSUE TITLE
[code2fn] M12 Updates to Code Model Coverage Tracker

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/skema#663]
For the Code Model Coverage Tracker report page:
https://ml4ai.github.io/skema/coverage/code2fn_coverage/report.html
... do the following:

```[tasklist]
### Tasks
- [x] Add the FN version number to which FN version is being generated.
- [x] Make each System Gromet entry include all of the grometFN in the Collection that are able to be ingested. If not complete, indicate `incomplete` in the entry.
- [x] At top of page, add a link to a model FNCollection index page that lists all of the current indices
- [x] Add MORAE ingestion as field
- [ ] Create additional consumer-facing summary page
- [x] Prevent include files from being processed
- [x] Reduce redundant operations
- [ ] Add developer documentation
```

**Comment by myedibleenso** [comment]
@vincentraymond-ua , this should be updated to reflect consumer-facing summary vs. dev-facing summary.
