### ISSUE TITLE
[code2FN] CISM Model Ingestion

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#698]
One of the target models that we want to ingest is the CISM model. This model consists primarily of Fortran code, but also has some Python and C/C++ code.

We want to be able to ingest as much of the model as possible, but we need to start somewhere.

(NOTE: the tasklist is a WIP)
```[tasklist]
### Tasks
- [x] Current Fortran coverage and what support is needed
- [x] Handling of the Python 2 constructs, investigate how to leverage tree sitter to support (NOTE: mostly failing on print statements)
```

Fortran coverage needed CAST:
```[tasklist]
### Tasks
- [ ] #701
- [ ] https://github.com/ml4ai/skema/issues/724
- [ ] https://github.com/ml4ai/skema/issues/721
- [x] [fortran] Support tab form Fortran source code (plan: handle via preprocessor/rewrite)
- [x] [fortran] Update CISM fortran to remove ASSIGN GO TOs (data/models/climate/CISM/code/cism_v3)
```

Fortran coverage needed Gromet:

```[tasklist]
### Tasks
- [ ] https://github.com/ml4ai/skema/issues/703
- [ ] #700
- [ ] https://github.com/ml4ai/skema/issues/719
- [ ] https://github.com/ml4ai/skema/issues/728
```

**Comment by myedibleenso** [comment]
Can we preprocess our Python files to stripe/comment out and `print` for the time being?
