### ISSUE TITLE
[code2FN] Basic GOTO Generation in Gromet

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#772]
In order to fully support Labels and GOTO Gromet generation, we need to add CAST generation support, Annotated CAST support, and Gromet generation support.
This issue specifically tracks basic GOTOs. Another issue will track the more complicated Computed GOTO case.

```[tasklist]
### Tasks
- [ ] CAST Generation (Vincent)
- [ ] Annotated CAST Support
- [ ] Gromet Generation
- [ ] Unit Tests (in conjunction with #752)
```
