### ISSUE TITLE
Python tree sitter: Comprehensions & Lambdas

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#779]
As part of porting the PyAST2CAST generation to tree-sitter, we're porting all the features that we currently support piece-by-piece.

This issue is to track support for Comprehensions (List, Dict) and Lambda expressions.
We group these two idioms together because the generation solution for these are all very similar.

```[tasklist]
### Tasks
- [x] CAST support for List/Dict Comprehensions
- [x] CAST support for Lambdas
- [x] CAST unit tests for List/Dict Comprehensions
- [x] CAST unit tests for Lambdas
```

**Comment by titomeister** [comment]
Test cases have been written. PR has been opened for review.
