### ISSUE TITLE
[M12] Ingestion of code library

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#782]
[1.12] Develop initial approach to automatically ingest library interface

```[tasklist]
### Tasks
- [ ] #783
- [ ] https://github.com/ml4ai/skema/issues/790
- [ ] https://github.com/ml4ai/skema/issues/798
- [ ] #791
- [ ] https://github.com/ml4ai/skema/issues/797
- [ ] https://github.com/ml4ai/skema/issues/795
```

We need some way of mapping that repo to a namespace in order to unify FNs (ex. https://github.com/scikit-learn/scikit-learn/tree/1.4.0-1 -> sklearn)
[12:22](https://mlbayes.slack.com/archives/CF1S834KH/p1707153777524789)

Some languages have a nice unified way of managing deps, while others are a bit of a mess.  This might be beyond M12 scope, but it would be helpful to brainstorm a bit about the design of a language-specific system component to discover a project’s dependencies.  For the M12 milestone, it is probably sufficient to specify the dependency/ies semi-manually (maybe changing our ingestion endpoint to support an optional arg which is a list of dep URLs?).
