### ISSUE TITLE
[Integration] Consolidation and Streamlining Documentation for AMR workflows

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#820]
This issue is for tracking an update to our unified service. The update would be a consolidation of certain workflows and expanding and streamlining our documentation. 

```[tasklist]
### Tasks
- [ ] Consolidation of Equation to AMR endpoints
- [ ] Consolidation of Code to AMR endpoints
- [ ] Consolidation of AMR alignment from text endpoints
- [ ] Update documentation
```
